#!/usr/bin/env python3
# Our own PURE tube transfer tables (Guitarix-style architecture, NOT its GPL code).
# Physics is public: Koren triode/pentode model (Norman Koren), datasheet SPICE
# constants, grid-conduction Igk=exp(7.75*Vgk-10.3), and the Yeh/Karjalainen
# load-line circuit solve (academic, DAFx). The table is the PURE plate transfer
# Ftube(Vgrid)->Vplate with NO cathode -- the cathode is modeled OUTSIDE in the
# stage's feedback loop (Rk, Ck, Vk0), exactly like a real cathode-biased stage.
import numpy as np

def Igk(Vgk):                                   # grid conduction current (A)
    return np.exp(np.clip(7.75*Vgk - 10.3, -80.0, 50.0))

def Ipk_triode(Vgk, Vpk, mu, ex, kg1, kp, kvb):
    a  = kp*(1.0/mu + Vgk/np.sqrt(kvb + Vpk*Vpk))
    E1 = (Vpk/kp)*np.log1p(np.exp(np.clip(a, -60.0, 60.0)))
    return np.where(E1 > 0.0, 2.0*np.power(np.maximum(E1, 0.0), ex)/kg1, 0.0)

def Ipk_pentode(Vgk, Vpk, mu, ex, kg1, kp, kvb, kg2):
    # screen tied for class-A: Koren pentode plate current
    E1 = (Vpk/kp)*np.log1p(np.exp(np.clip(kp*(1.0/mu + Vgk/Vpk), -60.0, 60.0)))
    G1 = 2.0*np.power(np.maximum(E1, 0.0), ex)/kg1*(E1 > 0.0)*np.arctan(Vpk/kvb)
    return G1/kg2 * kg2   # (kg2 folds into scale below; keep shape)

def solve_Vgk(Vi, Ri):
    # KVL at grid: Vi = Vgk + Ri*Igk(Vgk)  -> Newton for Vgk
    Vgk = np.minimum(Vi, 0.0).astype(float)
    for _ in range(80):
        f = Vi - Vgk - Ri*Igk(Vgk)
        d = -1.0 - Ri*7.75*Igk(Vgk)
        Vgk = Vgk - f/np.where(np.abs(d) < 1e-12, -1e-12, d)
    return Vgk

def solve_Vpk(Vgk, Vsupply, Rp, ipk, args):
    # load line: Vsupply = Vpk + Rp*Ipk(Vgk,Vpk)  -> Newton for Vpk
    Vpk = np.full_like(np.asarray(Vgk, float), Vsupply*0.5)
    h = 1e-2
    for _ in range(120):
        I0 = ipk(Vgk, Vpk, *args)
        f  = Vpk + Rp*I0 - Vsupply
        d  = 1.0 + Rp*(ipk(Vgk, Vpk + h, *args) - I0)/h
        step = f/np.where(np.abs(d) < 1e-9, 1e-9, d)
        Vpk = np.clip(Vpk - np.clip(step, -60.0, 60.0), 0.5, Vsupply)
    return Vpk

def build_triode(name, mu, ex, kg1, kp, kvb, Vsupply, Rp, Ri_list, Vmin, Vmax, N=2001):
    Vi = np.linspace(Vmin, Vmax, N)
    tabs, ranode = [], []
    for Ri in Ri_list:
        Vgk = solve_Vgk(Vi, Ri)
        Vp  = solve_Vpk(Vgk, Vsupply, Rp, Ipk_triode, (mu, ex, kg1, kp, kvb))
        # dynamic plate resistance Ranode = dVp/dIp
        h = (Vmax - Vmin)/(N-1)
        Vgk2 = solve_Vgk(Vi + h, Ri)
        Vp2  = solve_Vpk(Vgk2, Vsupply, Rp, Ipk_triode, (mu, ex, kg1, kp, kvb))
        Ip1 = Ipk_triode(Vgk,  Vp,  mu, ex, kg1, kp, kvb)
        Ip2 = Ipk_triode(Vgk2, Vp2, mu, ex, kg1, kp, kvb)
        ra  = np.where(np.abs(Ip2-Ip1) < 1e-12, 1e5, (Vp2-Vp)/(Ip2-Ip1))
        tabs.append((Ri, Vi, Vp)); ranode.append((Ri, Vi, np.abs(ra)))
    return Vi, tabs, ranode

def build_pentode_stage(name, mu, ex, kg1, kg2, kp, kvb, Vsupply, Rp, Ri_list, Vmin, Vmax, N=2001):
    Vi = np.linspace(Vmin, Vmax, N)
    tabs, ranode = [], []
    for Ri in Ri_list:
        Vgk = solve_Vgk(Vi, Ri)
        Vp  = solve_Vpk(Vgk, Vsupply, Rp, Ipk_pentode, (mu, ex, kg1, kp, kvb, kg2))
        h = (Vmax - Vmin)/(N-1)
        Vgk2 = solve_Vgk(Vi + h, Ri)
        Vp2  = solve_Vpk(Vgk2, Vsupply, Rp, Ipk_pentode, (mu, ex, kg1, kp, kvb, kg2))
        Ip1 = Ipk_pentode(Vgk,  Vp,  mu, ex, kg1, kp, kvb, kg2)
        Ip2 = Ipk_pentode(Vgk2, Vp2, mu, ex, kg1, kp, kvb, kg2)
        ra  = np.where(np.abs(Ip2-Ip1) < 1e-12, 1e6, (Vp2-Vp)/(Ip2-Ip1))
        tabs.append((Ri, Vi, Vp)); ranode.append((Ri, Vi, np.abs(ra)))
    return Vi, tabs, ranode

def emit(path, prefix, Vmin, Vmax, N, tabs, ranode=None):
    with open(path, 'w') as o:
        o.write('#pragma once\n// Generated by /tmp/gx_tube.py -- OUR pure Koren/Yeh tube transfer.\n')
        o.write('// Pure plate transfer Vgrid->Vplate (volts); cathode is external (stage loop).\n')
        o.write('namespace rbtube {\n')
        o.write('static constexpr int %s_N = %d;\n' % (prefix, N))
        o.write('static constexpr float %s_VMIN = %.6ff;\n' % (prefix, Vmin))
        o.write('static constexpr float %s_VMAX = %.6ff;\n' % (prefix, Vmax))
        for idx, (Ri, Vi, Vp) in enumerate(tabs):
            o.write('static const float %s_FT%d[%s_N] = {\n' % (prefix, idx, prefix))
            o.write(','.join('%.6ff' % v for v in Vp))
            o.write('\n};\n')
        if ranode:
            for idx, (Ri, Vi, ra) in enumerate(ranode):
                o.write('static const float %s_RA%d[%s_N] = {\n' % (prefix, idx, prefix))
                o.write(','.join('%.3ff' % v for v in ra))
                o.write('\n};\n')
        # linear-interp lookups, idx selects Ri table (0=low Ri, 1=high Ri)
        o.write('static inline float %s_ftube(int t, float v){\n' % prefix)
        o.write('  float x=(v-%s_VMIN)*((%s_N-1)/(%s_VMAX-%s_VMIN));\n' % (prefix,prefix,prefix,prefix))
        o.write('  if(x<=0)x=0; if(x>=%s_N-1)x=%s_N-1.001f;\n' % (prefix,prefix))
        o.write('  int i=(int)x; float fr=x-i; const float*T=(t?%s_FT1:%s_FT0);\n' % (prefix,prefix))
        o.write('  return T[i]+fr*(T[i+1]-T[i]);\n}\n')
        if ranode:
            o.write('static inline float %s_ranode(int t, float v){\n' % prefix)
            o.write('  float x=(v-%s_VMIN)*((%s_N-1)/(%s_VMAX-%s_VMIN));\n' % (prefix,prefix,prefix,prefix))
            o.write('  if(x<=0)x=0; if(x>=%s_N-1)x=%s_N-1.001f;\n' % (prefix,prefix))
            o.write('  int i=(int)x; float fr=x-i; const float*T=(t?%s_RA1:%s_RA0);\n' % (prefix,prefix))
            o.write('  return T[i]+fr*(T[i+1]-T[i]);\n}\n')
        o.write('} // namespace rbtube\n')

# 12AX7 preamp triode: public Koren constants, Vsupply=250, Rp=100k, Ri 68k/250k
Vi, tabs, ranode = build_triode('12AX7', 100.0, 1.4, 1060.0, 600.0, 300.0,
                                250.0, 100e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren12ax7_ftube.h',
     'AX7', -5.0, 5.0, len(Vi), tabs, ranode)

# sanity dump
for (Ri, _, Vp) in tabs:
    print('12AX7 Ri=%dk: Vp@rest(Vi=0)=%.1f  Vp@Vi=+3=%.1f  Vp@Vi=-3=%.1f'
          % (Ri/1e3, Vp[len(Vp)//2], Vp[int((3-(-5))/10*(len(Vp)-1))], Vp[int((-3-(-5))/10*(len(Vp)-1))]))
print('OK 12AX7 table written')

# ---- EL84 power pentode (AC30 class-A push-pull) ----
def Ipk_tp(Vgk,Vpk,mu,ex,kg1,kp,kvb):     # pentode (Koren, stable atan form)
    a = kp*(1.0/mu + Vgk/Vpk)
    E1 = (Vpk/kp)*np.log1p(np.exp(np.clip(a,-60.0,60.0)))
    return np.where(E1>0.0, 2.0*np.power(np.maximum(E1,0.0),ex)/kg1*np.arctan(Vpk/kvb), 0.0)

def build_pentode(name,mu,ex,kg1,kp,kvb,Vsupply,Rp,Ri,Vmin,Vmax,N=2001):
    Vi=np.linspace(Vmin,Vmax,N)
    Vgk=solve_Vgk(Vi,Ri)
    Vp=solve_Vpk(Vgk,Vsupply,Rp,Ipk_tp,(mu,ex,kg1,kp,kvb))
    return Vi,[(Ri,Vi,Vp),(Ri,Vi,Vp)]   # dup so emit's FT0/FT1 both exist

# EL84: mu21.3 ex1.24 kg1 401.7 kp111.1 kvb17.9; B+~300, PP plate load ~2k, grid-leak 220k
ViE,tabsE = build_pentode('EL84',21.3,1.24,401.7,111.1,17.9, 300.0, 2000.0, 220e3, -30.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_el84_ftube.h',
     'EL84', -30.0, 6.0, len(ViE), tabsE, None)
Vp=tabsE[0][2]
def at(v): 
    i=int((v-(-30.0))/(6.0-(-30.0))*(len(ViE)-1)); return Vp[i]
print('EL84 Vp@cutoff(Vg=-20)=%.0f  @bias(Vg=-8)=%.0f  @Vg=0=%.0f  @Vg=+4=%.0f'%(at(-20),at(-8),at(0),at(4)))
print('OK EL84 pentode table written')

# ---- 6BM8 / ECL82 power pentode (Gibson GA-8 family) ----
# RCA 6BM8/ECL82.pdf local datasheet:
#   Class A pentode unit: Va=200V, Vg2=200V, Vg1=-16V, Ia=35mA,
#   gm=6400umhos, rp~=20k, load=5.6k, Pout=3.5W, THD=10%.
# This table models the POWER PENTODE section only (not the built-in triode).
# The constants keep the EL84-style Koren curvature but scale KG1 so the RCA
# operating point lands at ~35mA. GA-8 uses two of these in push-pull, not EL84s.
ViBM8, tabsBM8 = build_pentode('6BM8', 9.5, 1.24, 647.4, 111.1, 17.9,
                               300.0, 2800.0, 220e3, -36.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6bm8_ftube.h',
     'BM8', -36.0, 6.0, len(ViBM8), tabsBM8, None)
VpBM8=tabsBM8[0][2]
def atBM8(v): i=int((v-(-36.0))/(6.0-(-36.0))*(len(ViBM8)-1)); return VpBM8[i]
print('6BM8 pentode cutoff(-28)=%.0f  RCA bias(-16)=%.0f  Vg0=%.0f  +4=%.0f'%(atBM8(-28),atBM8(-16),atBM8(0),atBM8(4)))
print('OK 6BM8 pentode table written')

# ---- 12AY7 preamp triode (5E3 V1: low-mu ~44, warm, early soft breakup) ----
Vi7, tabs7, ranode7 = build_triode('12AY7', 44.16, 1.11, 1192.4, 409.96, 300.0,
                                   250.0, 100e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren12ay7_ftube.h',
     'AY7', -5.0, 5.0, len(Vi7), tabs7, ranode7)
for (Ri,_,Vp) in tabs7:
    print('12AY7 Ri=%dk: rest=%.0f  +3=%.0f  -3=%.0f'%(Ri/1e3,Vp[len(Vp)//2],Vp[int(0.8*(len(Vp)-1))],Vp[int(0.2*(len(Vp)-1))]))

# ---- 6V6 power pentode (5E3: 2x 6V6 PP, cathode-biased) ----
Vi6, tabs6 = build_pentode('6V6', 12.67, 1.198, 915.0, 38.07, 30.2, 350.0, 2000.0, 220e3, -32.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6v6_ftube.h',
     'V6', -32.0, 6.0, len(Vi6), tabs6, None)
Vp6=tabs6[0][2]
def at6(v): i=int((v-(-32.0))/(6.0-(-32.0))*(len(Vi6)-1)); return Vp6[i]
print('6V6 cutoff(-22)=%.0f  bias(-12)=%.0f  Vg0=%.0f  +4=%.0f'%(at6(-22),at6(-12),at6(0),at6(4)))
print('OK 12AY7 + 6V6 tables written')

# ---- 12AT7 / ECC81 phase-inverter triode (Super-Sonic 22 PI) ----
# Tung-Sol 12AT7.pdf local datasheet: mu 60, at Va=250V with Rk=200R:
# Ia=10mA, gm=5500umhos, rp=10.9k. Constants below are fit to that operating
# point with the same public Koren triode equation used by the other preamp
# tables, so a 12AT7 LTP clips/loads differently from a 12AX7.
ViAT, tabsAT, ranodeAT = build_triode('12AT7', 60.0, 1.20, 507.8, 600.0, 300.0,
                                      250.0, 100e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren12at7_ftube.h',
     'AT7', -5.0, 5.0, len(ViAT), tabsAT, ranodeAT)
for (Ri,_,Vp) in tabsAT:
    print('12AT7 Ri=%dk: rest=%.0f  +3=%.0f  -3=%.0f'%(Ri/1e3,Vp[len(Vp)//2],Vp[int(0.8*(len(Vp)-1))],Vp[int(0.2*(len(Vp)-1))]))
print('OK 12AT7 table written')

# ---- 6EU7 low-noise high-mu twin triode (Gibson GA-79 preamps) ----
# RCA 6EU7.pdf: Va=250V, Vg=-2V, mu=100, rp=62.5k, gm=1600umhos, Ia=1.2mA.
# Electrically close to 12AX7, but with its own Miller capacitances.
ViEU7, tabsEU7, ranodeEU7 = build_triode('6EU7', 100.0, 1.4, 1060.0, 600.0, 300.0,
                                         250.0, 100e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6eu7_ftube.h',
     'EU7', -5.0, 5.0, len(ViEU7), tabsEU7, ranodeEU7)
for (Ri,_,Vp) in tabsEU7:
    print('6EU7 Ri=%dk: rest=%.0f  +3=%.0f  -3=%.0f'%(Ri/1e3,Vp[len(Vp)//2],Vp[int(0.8*(len(Vp)-1))],Vp[int(0.2*(len(Vp)-1))]))
print('OK 6EU7 table written')

# ---- 6SL7-GT high-mu twin triode (Epiphone Zephyr vintage driver/PI family) ----
# RCA 6SL7GT.pdf: Va=250V, Vg=-2V, mu=70, rp=44k, gm=1600umhos, Ia=2.3mA.
ViSL7, tabsSL7, ranodeSL7 = build_triode('6SL7GT', 70.0, 1.35, 1620.2, 600.0, 300.0,
                                         250.0, 100e3, [68e3, 250e3], -6.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6sl7_ftube.h',
     'SL7', -6.0, 6.0, len(ViSL7), tabsSL7, ranodeSL7)
for (Ri,_,Vp) in tabsSL7:
    print('6SL7 Ri=%dk: rest=%.0f  +3=%.0f  -3=%.0f'%(Ri/1e3,Vp[len(Vp)//2],Vp[int((3-(-6))/(12)*(len(Vp)-1))],Vp[int((-3-(-6))/(12)*(len(Vp)-1))]))
print('OK 6SL7 table written')

# ---- 6SF5 / 6SF5GT high-mu single triode (Epiphone Zephyr trem/recovery family) ----
# Tung-Sol 6SF5.pdf: Va=250V, Vg=-2V, mu=100, rp=66k, gm=1500umhos, Ia=0.9mA.
ViSF5, tabsSF5, ranodeSF5 = build_triode('6SF5', 100.0, 1.35, 1148.7, 600.0, 300.0,
                                         250.0, 100e3, [68e3, 250e3], -6.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6sf5_ftube.h',
     'SF5', -6.0, 6.0, len(ViSF5), tabsSF5, ranodeSF5)
for (Ri,_,Vp) in tabsSF5:
    print('6SF5 Ri=%dk: rest=%.0f  +3=%.0f  -3=%.0f'%(Ri/1e3,Vp[len(Vp)//2],Vp[int((3-(-6))/(12)*(len(Vp)-1))],Vp[int((-3-(-6))/(12)*(len(Vp)-1))]))
print('OK 6SF5 table written')

# ---- 12AU7 / ECC82 low-mu twin triode (GA-79 12AU7 phase inverter) ----
# Brimar 12AU7.pdf: Va=250V, Vg=-8.5V, mu=17, rp=7.7k, gm=2.2mA/V, Ia=10.5mA.
ViAU7, tabsAU7, ranodeAU7 = build_triode('12AU7', 17.0, 1.20, 1709.7, 600.0, 300.0,
                                         250.0, 100e3, [68e3, 250e3], -18.0, 8.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren12au7_ftube.h',
     'AU7', -18.0, 8.0, len(ViAU7), tabsAU7, ranodeAU7)
for (Ri,_,Vp) in tabsAU7:
    print('12AU7 Ri=%dk: rest=%.0f  +3=%.0f  -8.5=%.0f'%(Ri/1e3,Vp[len(Vp)//2],Vp[int((3-(-18))/(26)*(len(Vp)-1))],Vp[int((-8.5-(-18))/(26)*(len(Vp)-1))]))
print('OK 12AU7 table written')

# ---- 7199 triode section (GA-79 PI/reverb recovery family) ----
# Sylvania 7199.pdf: triode section Va=215V, Vg=-8.5V, mu=17, rp=8.1k,
# gm=2100umhos, Ia=9.0mA.
Vi7199T, tabs7199T, ranode7199T = build_triode('7199T', 17.0, 1.20, 1234.6, 600.0, 300.0,
                                               250.0, 100e3, [68e3, 250e3], -18.0, 8.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren7199t_ftube.h',
     'N99T', -18.0, 8.0, len(Vi7199T), tabs7199T, ranode7199T)
for (Ri,_,Vp) in tabs7199T:
    print('7199T Ri=%dk: rest=%.0f  +3=%.0f  -8.5=%.0f'%(Ri/1e3,Vp[len(Vp)//2],Vp[int((3-(-18))/(26)*(len(Vp)-1))],Vp[int((-8.5-(-18))/(26)*(len(Vp)-1))]))
print('OK 7199 triode table written')

# ---- EF86 small-signal pentode (Matchless DC30 channel 2) ----
# EF86.pdf local datasheet, Jan 1970: AF pentode, Va 250V, Vg2 140V,
# Vg1 -2.2V, Ia 3.0mA, gm 2.2mA/V, mu_g2g1 38, Ri 2.5M.
# DC30 schematic stage: 330k plate, 2M2 screen feed, 2k2 cathode + 25uF.
# Constants are the public Koren/Guitarix EF86 fit; the transfer table is generated
# here from our own load-line solve for the DC30's 330k plate stage.
ViEF, tabsEF, ranodeEF = build_pentode_stage('EF86', 34.9, 1.35, 2648.1, 4267.0, 222.06, 4.7,
                                             250.0, 330e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_ef86_ftube.h',
     'EF86', -5.0, 5.0, len(ViEF), tabsEF, ranodeEF)
VpEF=tabsEF[0][2]
def atEF(v): i=int((v-(-5.0))/(5.0-(-5.0))*(len(ViEF)-1)); return VpEF[i]
print('EF86 DC30 330k plate: Vg-3=%.0f bias(-2.2)=%.0f Vg-1=%.0f Vg0=%.0f Vg+1=%.0f'%(atEF(-3),atEF(-2.2),atEF(-1),atEF(0),atEF(1)))
print('OK EF86 table written')

# ---- 5879 small-signal sharp-cutoff pentode (Epiphone Zephyr input) ----
# RCA 5879.pdf: pentode connection Va=250V, Vg2=100V, Vg1=-3V,
# Ia=1.8mA, gm=1000umhos, rp~=2Mohm. Use a 220k load-line table for the
# vintage input pentode's high-impedance plate circuit.
Vi5879, tabs5879, ranode5879 = build_pentode_stage('5879', 34.9, 1.35, 11933.7, 4267.0, 222.06, 4.7,
                                                   250.0, 220e3, [68e3, 250e3], -8.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren5879_ftube.h',
     'N5879', -8.0, 5.0, len(Vi5879), tabs5879, ranode5879)
Vp5879=tabs5879[0][2]
def at5879(v): i=int((v-(-8.0))/(5.0-(-8.0))*(len(Vi5879)-1)); return Vp5879[i]
print('5879 220k plate: Vg-5=%.0f bias(-3)=%.0f Vg-1=%.0f Vg0=%.0f'%(at5879(-5),at5879(-3),at5879(-1),at5879(0)))
print('OK 5879 table written')

# ---- 7199 pentode section (GA-79 spring reverb driver) ----
# Sylvania 7199.pdf: pentode section can run hot at Va=220V, Vg2=130V,
# Rk=62R, Ia=12.5mA, gm=7000umhos. Model the reverb driver around that
# high-current point; screen voltage is folded into the fitted transfer.
Vi7199P, tabs7199P, ranode7199P = build_pentode_stage('7199P', 30.0, 1.35, 2996.8, 4267.0, 222.06, 4.7,
                                                     250.0, 100e3, [68e3, 250e3], -8.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren7199p_ftube.h',
     'N99P', -8.0, 5.0, len(Vi7199P), tabs7199P, ranode7199P)
Vp7199P=tabs7199P[0][2]
def at7199P(v): i=int((v-(-8.0))/(5.0-(-8.0))*(len(Vi7199P)-1)); return Vp7199P[i]
print('7199P 100k plate: Vg-4=%.0f Vg-2=%.0f hot(-1)=%.0f Vg0=%.0f'%(at7199P(-4),at7199P(-2),at7199P(-1),at7199P(0)))
print('OK 7199 pentode table written')

# ---- 6L6 legacy generic power pentode (kept for existing amp compatibility) ----
Vi5, tabs5 = build_pentode('6L6', 8.7, 1.35, 1460.0, 48.0, 12.0, 430.0, 2000.0, 220e3, -80.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6l6_ftube.h',
     'L6', -80.0, 6.0, len(Vi5), tabs5, None)
Vp5=tabs5[0][2]
def at5(v): i=int((v-(-80.0))/(6.0-(-80.0))*(len(Vi5)-1)); return Vp5[i]
print('6L6 cutoff(-60)=%.0f bias(-45)=%.0f Vg-20=%.0f Vg0=%.0f Vg+4=%.0f'%(at5(-60),at5(-45),at5(-20),at5(0),at5(4)))
print('OK 6L6 table written')

# ---- 6L6G coke-bottle beam pentode (Epiphone Zephyr/Ruby, lower-voltage 6L6) ----
# Sylvania 6L6G.pdf: "Electrically, the 6L6G and 6L6 are identical." Ratings are
# the older glass envelope: Va max 360V, Vg2 max 270V, Pa 19W. Typical PP AB1:
# Va=360V, Vg2=270V, bias=-22.5V, Raa=6.6k, Pout=26.5W. Use the same public
# 6L6 curvature constants, but a 360V / 6.6k-a-a load line (Rp ~= Raa/4).
Vi6G, tabs6G = build_pentode('6L6G', 8.7, 1.35, 1460.0, 48.0, 12.0,
                             360.0, 1650.0, 220e3, -70.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6l6g_ftube.h',
     'L6G', -70.0, 6.0, len(Vi6G), tabs6G, None)
Vp6G=tabs6G[0][2]
def at6G(v): i=int((v-(-70.0))/(6.0-(-70.0))*(len(Vi6G)-1)); return Vp6G[i]
print('6L6G cutoff(-55)=%.0f bias(-30)=%.0f bias(-22.5)=%.0f Vg0=%.0f Vg+4=%.0f'%(at6G(-55),at6G(-30),at6G(-22.5),at6G(0),at6G(4)))
print('OK 6L6G table written')

# ---- 5881 power beam pentode (Bassman/Bluesbreaker family, fixed bias) ----
# Tung-Sol 5881 datasheet: 400V max plate, 23W plate dissipation; AB1 data at
# 360V plate / 270V screen / Raa 6.6k / bias -22.5V. Guitar amps such as the
# 5F6-A Bassman run the 5881 harder, so this table keeps the Bassman-style
# 430V/8k-a-a load line but uses the softer 6L6GB/5881 constants.
Vi58, tabs58 = build_pentode('5881', 8.7, 1.26, 1210.3, 47.5, 11.6, 430.0, 2000.0, 220e3, -80.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren5881_ftube.h',
     'T5881', -80.0, 6.0, len(Vi58), tabs58, None)
Vp58=tabs58[0][2]
def at58(v): i=int((v-(-80.0))/(6.0-(-80.0))*(len(Vi58)-1)); return Vp58[i]
print('5881 cutoff(-60)=%.0f bias(-45)=%.0f Vg-22.5=%.0f Vg0=%.0f Vg+4=%.0f'%(at58(-60),at58(-45),at58(-22.5),at58(0),at58(4)))
print('OK 5881 table written')

# ---- 6L6GC high-power beam pentode (Mesa/ENGL/Boogie family, fixed bias) ----
# Tung-Sol 6L6GC datasheet: 500V plate max, 450V screen max, 30W plate
# dissipation; high-power PP AB1 point is 450V plate / 400V screen / Raa 5.6k /
# bias -37V / 55W. Use the same stable 6L6 Koren constants with that high-power
# load line so this is distinct from the softer 5881/Bassman table.
ViGC, tabsGC = build_pentode('6L6GC', 8.7, 1.35, 1460.0, 48.0, 12.0, 450.0, 1400.0, 220e3, -80.0, 8.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6l6gc_ftube.h',
     'L6GC', -80.0, 8.0, len(ViGC), tabsGC, None)
VpGC=tabsGC[0][2]
def atGC(v): i=int((v-(-80.0))/(8.0-(-80.0))*(len(ViGC)-1)); return VpGC[i]
print('6L6GC cutoff(-60)=%.0f bias(-45)=%.0f bias(-37)=%.0f Vg0=%.0f Vg+4=%.0f'%(atGC(-60),atGC(-45),atGC(-37),atGC(0),atGC(4)))
print('OK 6L6GC table written')

# ---- KT66 power beam tetrode (Budda/JTM45 family: 2x KT66 PP, fixed bias) ----
# Marconi KT66 datasheet, June 1956:
#   PP AB1 pentode: Va0 415V, Vg2 300V, Raa 8k, Pout 30W.
#   Fixed-bias high-power: Va0 510V, Vg2 395V, bias ~-40V, Raa 5k, Pout 50W.
# Use the 45W guitar-amp middle ground here: hot KT66 curvature from the public
# Koren/Guitarix constants, but a 470V supply and ~6.6k a-a OT equivalent
# (Rp ~= Raa/4) so it stays between JTM45 and the 50W datasheet point.
ViK, tabsK = build_pentode('KT66', 11.7, 1.98, 510.9, 34.9, 22.3,
                           470.0, 1650.0, 220e3, -82.0, 8.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_kt66_ftube.h',
     'KT66', -82.0, 8.0, len(ViK), tabsK, None)
VpK=tabsK[0][2]
def atK(v): i=int((v-(-82.0))/(8.0-(-82.0))*(len(ViK)-1)); return VpK[i]
print('KT66 cutoff(-65)=%.0f bias(-40)=%.0f Vg-20=%.0f Vg0=%.0f Vg+5=%.0f'%(atK(-65),atK(-40),atK(-20),atK(0),atK(5)))
print('OK KT66 table written')

# ---- EL34 power pentode (Marshall Plexi: 4x EL34 ~100W, fixed bias, NFB) ----
ViM, tabsM = build_pentode('EL34', 12.3, 1.17, 353.9, 61.1, 29.9, 470.0, 1700.0, 220e3, -70.0, 8.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_el34_ftube.h',
     'EL34P', -70.0, 8.0, len(ViM), tabsM, None)
VpM=tabsM[0][2]
def atM(v): i=int((v-(-70.0))/(8.0-(-70.0))*(len(ViM)-1)); return VpM[i]
print('EL34 cutoff(-55)=%.0f bias(-40)=%.0f Vg-15=%.0f Vg0=%.0f Vg+5=%.0f'%(atM(-55),atM(-40),atM(-15),atM(0),atM(5)))
print('OK EL34 table written')
