#!/usr/bin/env python3
# Our own PURE tube transfer tables (Guitarix-style architecture, NOT its GPL code).
# Physics is public: Koren triode/pentode model (Norman Koren), datasheet SPICE
# constants, grid-conduction Igk=exp(7.75*Vgk-10.3), and the Yeh/Karjalainen
# load-line circuit solve (academic, DAFx). The table is the PURE plate transfer
# Ftube(Vgrid)->Vplate with NO cathode -- the cathode is modeled OUTSIDE in the
# stage's feedback loop (Rk, Ck, Vk0), exactly like a real cathode-biased stage.
import numpy as np

def Igk(Vgk):                                   # grid conduction current (A)
    return np.exp(np.clip(7.75*Vgk - 10.3, -80.0, 50.0))

def Ipk_triode(Vgk, Vpk, mu, ex, kg1, kp, kvb):
    a  = kp*(1.0/mu + Vgk/np.sqrt(kvb + Vpk*Vpk))
    E1 = (Vpk/kp)*np.log1p(np.exp(np.clip(a, -60.0, 60.0)))
    return np.where(E1 > 0.0, 2.0*np.power(np.maximum(E1, 0.0), ex)/kg1, 0.0)

def Ipk_pentode(Vgk, Vpk, mu, ex, kg1, kp, kvb, kg2):
    # screen tied for class-A: Koren pentode plate current
    E1 = (Vpk/kp)*np.log1p(np.exp(np.clip(kp*(1.0/mu + Vgk/Vpk), -60.0, 60.0)))
    G1 = 2.0*np.power(np.maximum(E1, 0.0), ex)/kg1*(E1 > 0.0)*np.arctan(Vpk/kvb)
    return G1/kg2 * kg2   # (kg2 folds into scale below; keep shape)

def solve_Vgk(Vi, Ri):
    # KVL at grid: Vi = Vgk + Ri*Igk(Vgk)  -> Newton for Vgk
    Vgk = np.minimum(Vi, 0.0).astype(float)
    for _ in range(80):
        f = Vi - Vgk - Ri*Igk(Vgk)
        d = -1.0 - Ri*7.75*Igk(Vgk)
        Vgk = Vgk - f/np.where(np.abs(d) < 1e-12, -1e-12, d)
    return Vgk

def solve_Vpk(Vgk, Vsupply, Rp, ipk, args):
    # load line: Vsupply = Vpk + Rp*Ipk(Vgk,Vpk)  -> Newton for Vpk
    Vpk = np.full_like(np.asarray(Vgk, float), Vsupply*0.5)
    h = 1e-2
    for _ in range(120):
        I0 = ipk(Vgk, Vpk, *args)
        f  = Vpk + Rp*I0 - Vsupply
        d  = 1.0 + Rp*(ipk(Vgk, Vpk + h, *args) - I0)/h
        step = f/np.where(np.abs(d) < 1e-9, 1e-9, d)
        Vpk = np.clip(Vpk - np.clip(step, -60.0, 60.0), 0.5, Vsupply)
    return Vpk

def build_triode(name, mu, ex, kg1, kp, kvb, Vsupply, Rp, Ri_list, Vmin, Vmax, N=2001):
    Vi = np.linspace(Vmin, Vmax, N)
    tabs, ranode = [], []
    for Ri in Ri_list:
        Vgk = solve_Vgk(Vi, Ri)
        Vp  = solve_Vpk(Vgk, Vsupply, Rp, Ipk_triode, (mu, ex, kg1, kp, kvb))
        # dynamic plate resistance Ranode = dVp/dIp
        h = (Vmax - Vmin)/(N-1)
        Vgk2 = solve_Vgk(Vi + h, Ri)
        Vp2  = solve_Vpk(Vgk2, Vsupply, Rp, Ipk_triode, (mu, ex, kg1, kp, kvb))
        Ip1 = Ipk_triode(Vgk,  Vp,  mu, ex, kg1, kp, kvb)
        Ip2 = Ipk_triode(Vgk2, Vp2, mu, ex, kg1, kp, kvb)
        ra  = np.where(np.abs(Ip2-Ip1) < 1e-12, 1e5, (Vp2-Vp)/(Ip2-Ip1))
        tabs.append((Ri, Vi, Vp)); ranode.append((Ri, Vi, np.abs(ra)))
    return Vi, tabs, ranode

def build_pentode_stage(name, mu, ex, kg1, kg2, kp, kvb, Vsupply, Rp, Ri_list, Vmin, Vmax, N=2001):
    Vi = np.linspace(Vmin, Vmax, N)
    tabs, ranode = [], []
    for Ri in Ri_list:
        Vgk = solve_Vgk(Vi, Ri)
        Vp  = solve_Vpk(Vgk, Vsupply, Rp, Ipk_pentode, (mu, ex, kg1, kp, kvb, kg2))
        h = (Vmax - Vmin)/(N-1)
        Vgk2 = solve_Vgk(Vi + h, Ri)
        Vp2  = solve_Vpk(Vgk2, Vsupply, Rp, Ipk_pentode, (mu, ex, kg1, kp, kvb, kg2))
        Ip1 = Ipk_pentode(Vgk,  Vp,  mu, ex, kg1, kp, kvb, kg2)
        Ip2 = Ipk_pentode(Vgk2, Vp2, mu, ex, kg1, kp, kvb, kg2)
        ra  = np.where(np.abs(Ip2-Ip1) < 1e-12, 1e6, (Vp2-Vp)/(Ip2-Ip1))
        tabs.append((Ri, Vi, Vp)); ranode.append((Ri, Vi, np.abs(ra)))
    return Vi, tabs, ranode

def emit(path, prefix, Vmin, Vmax, N, tabs, ranode=None):
    with open(path, 'w') as o:
        o.write('#pragma once\n// Generated by /tmp/gx_tube.py -- OUR pure Koren/Yeh tube transfer.\n')
        o.write('// Pure plate transfer Vgrid->Vplate (volts); cathode is external (stage loop).\n')
        o.write('namespace rbtube {\n')
        o.write('static constexpr int %s_N = %d;\n' % (prefix, N))
        o.write('static constexpr float %s_VMIN = %.6ff;\n' % (prefix, Vmin))
        o.write('static constexpr float %s_VMAX = %.6ff;\n' % (prefix, Vmax))
        for idx, (Ri, Vi, Vp) in enumerate(tabs):
            o.write('static const float %s_FT%d[%s_N] = {\n' % (prefix, idx, prefix))
            o.write(','.join('%.6ff' % v for v in Vp))
            o.write('\n};\n')
        if ranode:
            for idx, (Ri, Vi, ra) in enumerate(ranode):
                o.write('static const float %s_RA%d[%s_N] = {\n' % (prefix, idx, prefix))
                o.write(','.join('%.3ff' % v for v in ra))
                o.write('\n};\n')
        # linear-interp lookups, idx selects Ri table (0=low Ri, 1=high Ri)
        o.write('static inline float %s_ftube(int t, float v){\n' % prefix)
        o.write('  float x=(v-%s_VMIN)*((%s_N-1)/(%s_VMAX-%s_VMIN));\n' % (prefix,prefix,prefix,prefix))
        o.write('  if(x<=0)x=0; if(x>=%s_N-1)x=%s_N-1.001f;\n' % (prefix,prefix))
        o.write('  int i=(int)x; float fr=x-i; const float*T=(t?%s_FT1:%s_FT0);\n' % (prefix,prefix))
        o.write('  return T[i]+fr*(T[i+1]-T[i]);\n}\n')
        if ranode:
            o.write('static inline float %s_ranode(int t, float v){\n' % prefix)
            o.write('  float x=(v-%s_VMIN)*((%s_N-1)/(%s_VMAX-%s_VMIN));\n' % (prefix,prefix,prefix,prefix))
            o.write('  if(x<=0)x=0; if(x>=%s_N-1)x=%s_N-1.001f;\n' % (prefix,prefix))
            o.write('  int i=(int)x; float fr=x-i; const float*T=(t?%s_RA1:%s_RA0);\n' % (prefix,prefix))
            o.write('  return T[i]+fr*(T[i+1]-T[i]);\n}\n')
        o.write('} // namespace rbtube\n')

# 12AX7 preamp triode: public Koren constants, Vsupply=250, Rp=100k, Ri 68k/250k
Vi, tabs, ranode = build_triode('12AX7', 100.0, 1.4, 1060.0, 600.0, 300.0,
                                250.0, 100e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren12ax7_ftube.h',
     'AX7', -5.0, 5.0, len(Vi), tabs, ranode)

# sanity dump
for (Ri, _, Vp) in tabs:
    print('12AX7 Ri=%dk: Vp@rest(Vi=0)=%.1f  Vp@Vi=+3=%.1f  Vp@Vi=-3=%.1f'
          % (Ri/1e3, Vp[len(Vp)//2], Vp[int((3-(-5))/10*(len(Vp)-1))], Vp[int((-3-(-5))/10*(len(Vp)-1))]))
print('OK 12AX7 table written')

# ---- EL84 power pentode (AC30 class-A push-pull) ----
def Ipk_tp(Vgk,Vpk,mu,ex,kg1,kp,kvb):     # pentode (Koren, stable atan form)
    a = kp*(1.0/mu + Vgk/Vpk)
    E1 = (Vpk/kp)*np.log1p(np.exp(np.clip(a,-60.0,60.0)))
    return np.where(E1>0.0, 2.0*np.power(np.maximum(E1,0.0),ex)/kg1*np.arctan(Vpk/kvb), 0.0)

def build_pentode(name,mu,ex,kg1,kp,kvb,Vsupply,Rp,Ri,Vmin,Vmax,N=2001):
    Vi=np.linspace(Vmin,Vmax,N)
    Vgk=solve_Vgk(Vi,Ri)
    Vp=solve_Vpk(Vgk,Vsupply,Rp,Ipk_tp,(mu,ex,kg1,kp,kvb))
    return Vi,[(Ri,Vi,Vp),(Ri,Vi,Vp)]   # dup so emit's FT0/FT1 both exist

# EL84: mu21.3 ex1.24 kg1 401.7 kp111.1 kvb17.9; B+~300, PP plate load ~2k, grid-leak 220k
ViE,tabsE = build_pentode('EL84',21.3,1.24,401.7,111.1,17.9, 300.0, 2000.0, 220e3, -30.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_el84_ftube.h',
     'EL84', -30.0, 6.0, len(ViE), tabsE, None)
Vp=tabsE[0][2]
def at(v): 
    i=int((v-(-30.0))/(6.0-(-30.0))*(len(ViE)-1)); return Vp[i]
print('EL84 Vp@cutoff(Vg=-20)=%.0f  @bias(Vg=-8)=%.0f  @Vg=0=%.0f  @Vg=+4=%.0f'%(at(-20),at(-8),at(0),at(4)))
print('OK EL84 pentode table written')

# ---- 12AY7 preamp triode (5E3 V1: low-mu ~44, warm, early soft breakup) ----
Vi7, tabs7, ranode7 = build_triode('12AY7', 44.16, 1.11, 1192.4, 409.96, 300.0,
                                   250.0, 100e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren12ay7_ftube.h',
     'AY7', -5.0, 5.0, len(Vi7), tabs7, ranode7)
for (Ri,_,Vp) in tabs7:
    print('12AY7 Ri=%dk: rest=%.0f  +3=%.0f  -3=%.0f'%(Ri/1e3,Vp[len(Vp)//2],Vp[int(0.8*(len(Vp)-1))],Vp[int(0.2*(len(Vp)-1))]))

# ---- 6V6 power pentode (5E3: 2x 6V6 PP, cathode-biased) ----
Vi6, tabs6 = build_pentode('6V6', 12.67, 1.198, 915.0, 38.07, 30.2, 350.0, 2000.0, 220e3, -32.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6v6_ftube.h',
     'V6', -32.0, 6.0, len(Vi6), tabs6, None)
Vp6=tabs6[0][2]
def at6(v): i=int((v-(-32.0))/(6.0-(-32.0))*(len(Vi6)-1)); return Vp6[i]
print('6V6 cutoff(-22)=%.0f  bias(-12)=%.0f  Vg0=%.0f  +4=%.0f'%(at6(-22),at6(-12),at6(0),at6(4)))
print('OK 12AY7 + 6V6 tables written')

# ---- EF86 small-signal pentode (Matchless DC30 channel 2) ----
# EF86.pdf local datasheet, Jan 1970: AF pentode, Va 250V, Vg2 140V,
# Vg1 -2.2V, Ia 3.0mA, gm 2.2mA/V, mu_g2g1 38, Ri 2.5M.
# DC30 schematic stage: 330k plate, 2M2 screen feed, 2k2 cathode + 25uF.
# Constants are the public Koren/Guitarix EF86 fit; the transfer table is generated
# here from our own load-line solve for the DC30's 330k plate stage.
ViEF, tabsEF, ranodeEF = build_pentode_stage('EF86', 34.9, 1.35, 2648.1, 4267.0, 222.06, 4.7,
                                             250.0, 330e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_ef86_ftube.h',
     'EF86', -5.0, 5.0, len(ViEF), tabsEF, ranodeEF)
VpEF=tabsEF[0][2]
def atEF(v): i=int((v-(-5.0))/(5.0-(-5.0))*(len(ViEF)-1)); return VpEF[i]
print('EF86 DC30 330k plate: Vg-3=%.0f bias(-2.2)=%.0f Vg-1=%.0f Vg0=%.0f Vg+1=%.0f'%(atEF(-3),atEF(-2.2),atEF(-1),atEF(0),atEF(1)))
print('OK EF86 table written')

# ---- 6L6 legacy generic power pentode (kept for existing amp compatibility) ----
Vi5, tabs5 = build_pentode('6L6', 8.7, 1.35, 1460.0, 48.0, 12.0, 430.0, 2000.0, 220e3, -80.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6l6_ftube.h',
     'L6', -80.0, 6.0, len(Vi5), tabs5, None)
Vp5=tabs5[0][2]
def at5(v): i=int((v-(-80.0))/(6.0-(-80.0))*(len(Vi5)-1)); return Vp5[i]
print('6L6 cutoff(-60)=%.0f bias(-45)=%.0f Vg-20=%.0f Vg0=%.0f Vg+4=%.0f'%(at5(-60),at5(-45),at5(-20),at5(0),at5(4)))
print('OK 6L6 table written')

# ---- 5881 power beam pentode (Bassman/Bluesbreaker family, fixed bias) ----
# Tung-Sol 5881 datasheet: 400V max plate, 23W plate dissipation; AB1 data at
# 360V plate / 270V screen / Raa 6.6k / bias -22.5V. Guitar amps such as the
# 5F6-A Bassman run the 5881 harder, so this table keeps the Bassman-style
# 430V/8k-a-a load line but uses the softer 6L6GB/5881 constants.
Vi58, tabs58 = build_pentode('5881', 8.7, 1.26, 1210.3, 47.5, 11.6, 430.0, 2000.0, 220e3, -80.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren5881_ftube.h',
     'T5881', -80.0, 6.0, len(Vi58), tabs58, None)
Vp58=tabs58[0][2]
def at58(v): i=int((v-(-80.0))/(6.0-(-80.0))*(len(Vi58)-1)); return Vp58[i]
print('5881 cutoff(-60)=%.0f bias(-45)=%.0f Vg-22.5=%.0f Vg0=%.0f Vg+4=%.0f'%(at58(-60),at58(-45),at58(-22.5),at58(0),at58(4)))
print('OK 5881 table written')

# ---- 6L6GC high-power beam pentode (Mesa/ENGL/Boogie family, fixed bias) ----
# Tung-Sol 6L6GC datasheet: 500V plate max, 450V screen max, 30W plate
# dissipation; high-power PP AB1 point is 450V plate / 400V screen / Raa 5.6k /
# bias -37V / 55W. Use the same stable 6L6 Koren constants with that high-power
# load line so this is distinct from the softer 5881/Bassman table.
ViGC, tabsGC = build_pentode('6L6GC', 8.7, 1.35, 1460.0, 48.0, 12.0, 450.0, 1400.0, 220e3, -80.0, 8.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6l6gc_ftube.h',
     'L6GC', -80.0, 8.0, len(ViGC), tabsGC, None)
VpGC=tabsGC[0][2]
def atGC(v): i=int((v-(-80.0))/(8.0-(-80.0))*(len(ViGC)-1)); return VpGC[i]
print('6L6GC cutoff(-60)=%.0f bias(-45)=%.0f bias(-37)=%.0f Vg0=%.0f Vg+4=%.0f'%(atGC(-60),atGC(-45),atGC(-37),atGC(0),atGC(4)))
print('OK 6L6GC table written')

# ---- KT66 power beam tetrode (Budda/JTM45 family: 2x KT66 PP, fixed bias) ----
# Marconi KT66 datasheet, June 1956:
#   PP AB1 pentode: Va0 415V, Vg2 300V, Raa 8k, Pout 30W.
#   Fixed-bias high-power: Va0 510V, Vg2 395V, bias ~-40V, Raa 5k, Pout 50W.
# Use the 45W guitar-amp middle ground here: hot KT66 curvature from the public
# Koren/Guitarix constants, but a 470V supply and ~6.6k a-a OT equivalent
# (Rp ~= Raa/4) so it stays between JTM45 and the 50W datasheet point.
ViK, tabsK = build_pentode('KT66', 11.7, 1.98, 510.9, 34.9, 22.3,
                           470.0, 1650.0, 220e3, -82.0, 8.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_kt66_ftube.h',
     'KT66', -82.0, 8.0, len(ViK), tabsK, None)
VpK=tabsK[0][2]
def atK(v): i=int((v-(-82.0))/(8.0-(-82.0))*(len(ViK)-1)); return VpK[i]
print('KT66 cutoff(-65)=%.0f bias(-40)=%.0f Vg-20=%.0f Vg0=%.0f Vg+5=%.0f'%(atK(-65),atK(-40),atK(-20),atK(0),atK(5)))
print('OK KT66 table written')

# ---- EL34 power pentode (Marshall Plexi: 4x EL34 ~100W, fixed bias, NFB) ----
ViM, tabsM = build_pentode('EL34', 12.3, 1.17, 353.9, 61.1, 29.9, 470.0, 1700.0, 220e3, -70.0, 8.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_el34_ftube.h',
     'EL34P', -70.0, 8.0, len(ViM), tabsM, None)
VpM=tabsM[0][2]
def atM(v): i=int((v-(-70.0))/(8.0-(-70.0))*(len(ViM)-1)); return VpM[i]
print('EL34 cutoff(-55)=%.0f bias(-40)=%.0f Vg-15=%.0f Vg0=%.0f Vg+5=%.0f'%(atM(-55),atM(-40),atM(-15),atM(0),atM(5)))
print('OK EL34 table written')
