#!/usr/bin/env python3
# Our own PURE tube transfer tables (Guitarix-style architecture, NOT its GPL code).
# Physics is public: Koren triode/pentode model (Norman Koren), datasheet SPICE
# constants, grid-conduction Igk=exp(7.75*Vgk-10.3), and the Yeh/Karjalainen
# load-line circuit solve (academic, DAFx). The table is the PURE plate transfer
# Ftube(Vgrid)->Vplate with NO cathode -- the cathode is modeled OUTSIDE in the
# stage's feedback loop (Rk, Ck, Vk0), exactly like a real cathode-biased stage.
import numpy as np

def Igk(Vgk):                                   # grid conduction current (A)
    return np.exp(np.clip(7.75*Vgk - 10.3, -80.0, 50.0))

def Ipk_triode(Vgk, Vpk, mu, ex, kg1, kp, kvb):
    a  = kp*(1.0/mu + Vgk/np.sqrt(kvb + Vpk*Vpk))
    E1 = (Vpk/kp)*np.log1p(np.exp(np.clip(a, -60.0, 60.0)))
    return np.where(E1 > 0.0, 2.0*np.power(np.maximum(E1, 0.0), ex)/kg1, 0.0)

def Ipk_pentode(Vgk, Vpk, mu, ex, kg1, kp, kvb, kg2):
    # screen tied for class-A: Koren pentode plate current
    E1 = (Vpk/kp)*np.log1p(np.exp(np.clip(kp*(1.0/mu + Vgk/Vpk), -60.0, 60.0)))
    G1 = 2.0*np.power(np.maximum(E1, 0.0), ex)/kg1*(E1 > 0.0)*np.arctan(Vpk/kvb)
    return G1/kg2 * kg2   # (kg2 folds into scale below; keep shape)

def solve_Vgk(Vi, Ri):
    # KVL at grid: Vi = Vgk + Ri*Igk(Vgk)  -> Newton for Vgk
    Vgk = np.minimum(Vi, 0.0).astype(float)
    for _ in range(80):
        f = Vi - Vgk - Ri*Igk(Vgk)
        d = -1.0 - Ri*7.75*Igk(Vgk)
        Vgk = Vgk - f/np.where(np.abs(d) < 1e-12, -1e-12, d)
    return Vgk

def solve_Vpk(Vgk, Vsupply, Rp, ipk, args):
    # load line: Vsupply = Vpk + Rp*Ipk(Vgk,Vpk)  -> Newton for Vpk
    Vpk = np.full_like(np.asarray(Vgk, float), Vsupply*0.5)
    h = 1e-2
    for _ in range(120):
        I0 = ipk(Vgk, Vpk, *args)
        f  = Vpk + Rp*I0 - Vsupply
        d  = 1.0 + Rp*(ipk(Vgk, Vpk + h, *args) - I0)/h
        step = f/np.where(np.abs(d) < 1e-9, 1e-9, d)
        Vpk = np.clip(Vpk - np.clip(step, -60.0, 60.0), 0.5, Vsupply)
    return Vpk

def build_triode(name, mu, ex, kg1, kp, kvb, Vsupply, Rp, Ri_list, Vmin, Vmax, N=2001):
    Vi = np.linspace(Vmin, Vmax, N)
    tabs, ranode = [], []
    for Ri in Ri_list:
        Vgk = solve_Vgk(Vi, Ri)
        Vp  = solve_Vpk(Vgk, Vsupply, Rp, Ipk_triode, (mu, ex, kg1, kp, kvb))
        # dynamic plate resistance Ranode = dVp/dIp
        h = (Vmax - Vmin)/(N-1)
        Vgk2 = solve_Vgk(Vi + h, Ri)
        Vp2  = solve_Vpk(Vgk2, Vsupply, Rp, Ipk_triode, (mu, ex, kg1, kp, kvb))
        Ip1 = Ipk_triode(Vgk,  Vp,  mu, ex, kg1, kp, kvb)
        Ip2 = Ipk_triode(Vgk2, Vp2, mu, ex, kg1, kp, kvb)
        ra  = np.where(np.abs(Ip2-Ip1) < 1e-12, 1e5, (Vp2-Vp)/(Ip2-Ip1))
        tabs.append((Ri, Vi, Vp)); ranode.append((Ri, Vi, np.abs(ra)))
    return Vi, tabs, ranode

def emit(path, prefix, Vmin, Vmax, N, tabs, ranode=None):
    with open(path, 'w') as o:
        o.write('#pragma once\n// Generated by /tmp/gx_tube.py -- OUR pure Koren/Yeh tube transfer.\n')
        o.write('// Pure plate transfer Vgrid->Vplate (volts); cathode is external (stage loop).\n')
        o.write('namespace rbtube {\n')
        o.write('static constexpr int %s_N = %d;\n' % (prefix, N))
        o.write('static constexpr float %s_VMIN = %.6ff;\n' % (prefix, Vmin))
        o.write('static constexpr float %s_VMAX = %.6ff;\n' % (prefix, Vmax))
        for idx, (Ri, Vi, Vp) in enumerate(tabs):
            o.write('static const float %s_FT%d[%s_N] = {\n' % (prefix, idx, prefix))
            o.write(','.join('%.6ff' % v for v in Vp))
            o.write('\n};\n')
        if ranode:
            for idx, (Ri, Vi, ra) in enumerate(ranode):
                o.write('static const float %s_RA%d[%s_N] = {\n' % (prefix, idx, prefix))
                o.write(','.join('%.3ff' % v for v in ra))
                o.write('\n};\n')
        # linear-interp lookups, idx selects Ri table (0=low Ri, 1=high Ri)
        o.write('static inline float %s_ftube(int t, float v){\n' % prefix)
        o.write('  float x=(v-%s_VMIN)*((%s_N-1)/(%s_VMAX-%s_VMIN));\n' % (prefix,prefix,prefix,prefix))
        o.write('  if(x<=0)x=0; if(x>=%s_N-1)x=%s_N-1.001f;\n' % (prefix,prefix))
        o.write('  int i=(int)x; float fr=x-i; const float*T=(t?%s_FT1:%s_FT0);\n' % (prefix,prefix))
        o.write('  return T[i]+fr*(T[i+1]-T[i]);\n}\n')
        if ranode:
            o.write('static inline float %s_ranode(int t, float v){\n' % prefix)
            o.write('  float x=(v-%s_VMIN)*((%s_N-1)/(%s_VMAX-%s_VMIN));\n' % (prefix,prefix,prefix,prefix))
            o.write('  if(x<=0)x=0; if(x>=%s_N-1)x=%s_N-1.001f;\n' % (prefix,prefix))
            o.write('  int i=(int)x; float fr=x-i; const float*T=(t?%s_RA1:%s_RA0);\n' % (prefix,prefix))
            o.write('  return T[i]+fr*(T[i+1]-T[i]);\n}\n')
        o.write('} // namespace rbtube\n')

# 12AX7 preamp triode: public Koren constants, Vsupply=250, Rp=100k, Ri 68k/250k
Vi, tabs, ranode = build_triode('12AX7', 100.0, 1.4, 1060.0, 600.0, 300.0,
                                250.0, 100e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren12ax7_ftube.h',
     'AX7', -5.0, 5.0, len(Vi), tabs, ranode)

# sanity dump
for (Ri, _, Vp) in tabs:
    print('12AX7 Ri=%dk: Vp@rest(Vi=0)=%.1f  Vp@Vi=+3=%.1f  Vp@Vi=-3=%.1f'
          % (Ri/1e3, Vp[len(Vp)//2], Vp[int((3-(-5))/10*(len(Vp)-1))], Vp[int((-3-(-5))/10*(len(Vp)-1))]))
print('OK 12AX7 table written')

# ---- EL84 power pentode (AC30 class-A push-pull) ----
def Ipk_tp(Vgk,Vpk,mu,ex,kg1,kp,kvb):     # pentode (Koren, stable atan form)
    a = kp*(1.0/mu + Vgk/Vpk)
    E1 = (Vpk/kp)*np.log1p(np.exp(np.clip(a,-60.0,60.0)))
    return np.where(E1>0.0, 2.0*np.power(np.maximum(E1,0.0),ex)/kg1*np.arctan(Vpk/kvb), 0.0)

def build_pentode(name,mu,ex,kg1,kp,kvb,Vsupply,Rp,Ri,Vmin,Vmax,N=2001):
    Vi=np.linspace(Vmin,Vmax,N)
    Vgk=solve_Vgk(Vi,Ri)
    Vp=solve_Vpk(Vgk,Vsupply,Rp,Ipk_tp,(mu,ex,kg1,kp,kvb))
    return Vi,[(Ri,Vi,Vp),(Ri,Vi,Vp)]   # dup so emit's FT0/FT1 both exist

# EL84: mu21.3 ex1.24 kg1 401.7 kp111.1 kvb17.9; B+~300, PP plate load ~2k, grid-leak 220k
ViE,tabsE = build_pentode('EL84',21.3,1.24,401.7,111.1,17.9, 300.0, 2000.0, 220e3, -30.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_el84_ftube.h',
     'EL84', -30.0, 6.0, len(ViE), tabsE, None)
Vp=tabsE[0][2]
def at(v): 
    i=int((v-(-30.0))/(6.0-(-30.0))*(len(ViE)-1)); return Vp[i]
print('EL84 Vp@cutoff(Vg=-20)=%.0f  @bias(Vg=-8)=%.0f  @Vg=0=%.0f  @Vg=+4=%.0f'%(at(-20),at(-8),at(0),at(4)))
print('OK EL84 pentode table written')

# ---- 12AY7 preamp triode (5E3 V1: low-mu ~44, warm, early soft breakup) ----
Vi7, tabs7, ranode7 = build_triode('12AY7', 44.16, 1.11, 1192.4, 409.96, 300.0,
                                   250.0, 100e3, [68e3, 250e3], -5.0, 5.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren12ay7_ftube.h',
     'AY7', -5.0, 5.0, len(Vi7), tabs7, ranode7)
for (Ri,_,Vp) in tabs7:
    print('12AY7 Ri=%dk: rest=%.0f  +3=%.0f  -3=%.0f'%(Ri/1e3,Vp[len(Vp)//2],Vp[int(0.8*(len(Vp)-1))],Vp[int(0.2*(len(Vp)-1))]))

# ---- 6V6 power pentode (5E3: 2x 6V6 PP, cathode-biased) ----
Vi6, tabs6 = build_pentode('6V6', 12.67, 1.198, 915.0, 38.07, 30.2, 350.0, 2000.0, 220e3, -32.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6v6_ftube.h',
     'V6', -32.0, 6.0, len(Vi6), tabs6, None)
Vp6=tabs6[0][2]
def at6(v): i=int((v-(-32.0))/(6.0-(-32.0))*(len(Vi6)-1)); return Vp6[i]
print('6V6 cutoff(-22)=%.0f  bias(-12)=%.0f  Vg0=%.0f  +4=%.0f'%(at6(-22),at6(-12),at6(0),at6(4)))
print('OK 12AY7 + 6V6 tables written')

# ---- 6L6 / 5881 power pentode (Bassman 5F6-A: 2x 5881 PP, fixed bias, NFB) ----
Vi5, tabs5 = build_pentode('6L6', 8.7, 1.35, 1460.0, 48.0, 12.0, 430.0, 2000.0, 220e3, -80.0, 6.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren6l6_ftube.h',
     'L6', -80.0, 6.0, len(Vi5), tabs5, None)
Vp5=tabs5[0][2]
def at5(v): i=int((v-(-80.0))/(6.0-(-80.0))*(len(Vi5)-1)); return Vp5[i]
print('6L6 cutoff(-60)=%.0f bias(-45)=%.0f Vg-20=%.0f Vg0=%.0f Vg+4=%.0f'%(at5(-60),at5(-45),at5(-20),at5(0),at5(4)))
print('OK 6L6 table written')

# ---- EL34 power pentode (Marshall Plexi: 4x EL34 ~100W, fixed bias, NFB) ----
ViM, tabsM = build_pentode('EL34', 12.3, 1.17, 353.9, 61.1, 29.9, 470.0, 1700.0, 220e3, -70.0, 8.0)
emit('/Users/nacho/Files/slopsmith/rig_builder/vst/src/_shared/koren_el34_ftube.h',
     'EL34P', -70.0, 8.0, len(ViM), tabsM, None)
VpM=tabsM[0][2]
def atM(v): i=int((v-(-70.0))/(8.0-(-70.0))*(len(ViM)-1)); return VpM[i]
print('EL34 cutoff(-55)=%.0f bias(-40)=%.0f Vg-15=%.0f Vg0=%.0f Vg+5=%.0f'%(atM(-55),atM(-40),atM(-15),atM(0),atM(5)))
print('OK EL34 table written')
