#!/usr/bin/make -f

NAME = OilCanEcho

FILES_DSP = \
	OilCanEchoPlugin.cpp

FILES_UI = \
	OilCanEcho_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
