#!/usr/bin/make -f
# SBR Super Redhead — SWR Super Redhead bass preamp model (DPF plugin)

NAME = SbrRedhead

FILES_DSP = \
	RedheadPlugin.cpp

FILES_UI = \
	Redhead_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
