#!/usr/bin/make -f

NAME = PlateVerb

FILES_DSP = \
	PlateVerbPlugin.cpp

FILES_UI = \
	PlateVerb_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
