#!/usr/bin/make -f

NAME = Superdrive45

FILES_DSP = \
	SuperdrivePlugin.cpp

FILES_UI = \
	Superdrive_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
