#!/usr/bin/env python3
"""Genera los IRs Real Cab para TODOS los cabs de guitarra y bajo del juego.

Para cada cab de `data/real_cab_catalog.json` renderiza el modelo físico
(rb_core/cab_synth.py — driver por datasheet + caja por configuración + mic
+ posición) en la grilla de micrófonos/posiciones que usa Rocksmith:

    mic: dyn (SM57) · cond (TLM103) · ribbon (R121) · tube (U47 prov.)
    pos: cone (x=0.15, 1") · edge (x=0.85, 1") · offaxis (x=0.30, 2", 45°)

Los wav caen en `assets/cab_irs/<NombreClon>/<mic>_<pos>.wav` — una carpeta
por cab, nombrada con el nombre CLON del catálogo (no el real/marca), ej.
`assets/cab_irs/Box_AC30_2x12/dyn_cone.wav`. El instalador de setup() copia el
árbol a <config>/nam_irs/cabs/ y `data/rb_cab_overrides.json` se reescribe
(ir_dir=cabs/<NombreClon>, prefix="") — con eso `_apply_cab_override` hace que
TODAS las canciones usen estos IRs sin re-seed, y el mic-position picker del
editor los sirve como "IR propio".

Uso:  cd rig_builder && python3 tools/generate_real_cab_irs.py
      python3 tools/generate_real_cab_irs.py --gear Cab_EN212C --gear Cab_GB412CMKI
"""

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE))
from rb_core import cab_synth  # noqa: E402

MICS = {"dyn": "sm57", "cond": "tlm103", "ribbon": "r121", "tube": "tube"}
POSITIONS = {
    "cone":    {"x": 0.15, "dist_in": 1.0, "angle_deg": 0.0},
    # Edge at x=0.85 buried the presence range (2.5-8k rolled -2..-8 dB on top
    # of the +8 dB LF proximity lift) - songs seeded to the Edge voicing played
    # "blanketed" next to their RS versions. x=0.60 keeps the edge character
    # (fat lows, softened top) while retaining articulation; our model's radial
    # interference dip at 2.5k is also shallowest around here (worst near 0.70).
    "edge":    {"x": 0.60, "dist_in": 1.0, "angle_deg": 0.0},
    "offaxis": {"x": 0.30, "dist_in": 2.0, "angle_deg": 45.0},
}


def clone_slug(name: str) -> str:
    """Filesystem-safe folder name from a catalog clone name.
    "Mr. Y Maz 4x12" -> "Mr_Y_Maz_4x12";  "Ronald JC-120 2x12" -> "Ronald_JC-120_2x12".
    Must stay in sync with the migration used to lay out assets/cab_irs."""
    s = name.strip().replace(".", "")
    s = re.sub(r"[^0-9A-Za-z_-]+", "_", s)
    return re.sub(r"_+", "_", s).strip("_")


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--gear", action="append", default=[], metavar="GEAR_ID",
        help="render only this catalog gear (repeatable); default: all")
    return parser.parse_args()


def main():
    args = parse_args()
    cat = json.load(open(HERE / "data" / "real_cab_catalog.json"))
    out_dir = HERE / "assets" / "cab_irs"
    out_dir.mkdir(parents=True, exist_ok=True)

    overrides_path = HERE / "data" / "rb_cab_overrides.json"
    if args.gear and overrides_path.exists():
        overrides = json.load(open(overrides_path))
    else:
        overrides = {
            "_meta": ("OUR own cab IRs that OVERRIDE the Rocksmith-extracted "
                      "mic-position table. Generated by tools/generate_real_cab_irs.py "
                      "from the Real Cab parametric model (rb_core/cab_synth.py): "
                      "datasheet-driven drivers + per-configuration enclosure physics "
                      "+ spec-sheet mic models, validated vs measured reference grids "
                      "(see Cabs/CAB_MODELING_GUIDE.md). 100%% distributable — no "
                      "third-party IRs. One entry per cab gear key; files derive as "
                      "<ir_dir>/<mic>_<pos>.wav (ir_dir already includes the "
                      "clone-named per-cab subfolder)."),
        }
    selected = set(args.gear)
    missing = selected.difference(cat["cabs"])
    if missing:
        raise SystemExit("unknown gear id(s): " + ", ".join(sorted(missing)))

    n = 0
    for gear, entry in sorted(cat["cabs"].items()):
        if selected and gear not in selected:
            continue
        sub = clone_slug(entry.get("name") or gear)   # clone name, NOT the real brand
        cab_dir = out_dir / sub
        cab_dir.mkdir(parents=True, exist_ok=True)
        for mic_tok, mic in MICS.items():
            for pos_tok, pp in POSITIONS.items():
                out = cab_dir / f"{mic_tok}_{pos_tok}.wav"
                cab_synth.synthesize_ir_wav(
                    str(out), speaker=entry["speaker"], mic=mic,
                    x=pp["x"], dist_in=pp["dist_in"], angle_deg=pp["angle_deg"],
                    drivers=int(entry["drivers"]), size_in=float(entry["size_in"]),
                    back=entry["back"], baffle_m=float(entry["baffle_m"]),
                    voicing=entry.get("voicing"),
                    **cab_synth.enclosure_kwargs(entry))
                n += 1
        if entry.get("voicing"):
            desc = f"voicing '{entry['voicing']}'"
            source = (f"Real Cab novelty voicing model: {entry['voicing']} "
                      f"(character curve, cab_synth.py VOICINGS)")
        else:
            desc = (f"{entry['speaker']} {entry['drivers']}x{entry['size_in']} "
                    f"{entry['back']}")
            driver_basis = ("documented proxy" if entry.get("speaker_proxy")
                            else "datasheet-driven")
            source = (f"Real Cab parametric model: {entry['speaker']} "
                      f"{entry['drivers']}x{entry['size_in']} {entry['back']}-back "
                      f"({driver_basis}, cab_synth.py); "
                      f"{entry.get('enclosure_source', 'generic enclosure geometry')}")
        overrides[gear] = {"ir_dir": "cabs/" + sub, "prefix": "", "source": source}
        print(f"  ✓ {gear:<24} → cabs/{sub} ({desc})")

    with open(overrides_path, "w", encoding="utf-8") as fh:
        json.dump(overrides, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    print(f"\n{n} IRs → {out_dir}")
    print(f"{len(overrides) - 1} cabs registrados en rb_cab_overrides.json")


if __name__ == "__main__":
    main()
