#!/usr/bin/env python3
"""Genera los IRs Real Cab para TODOS los cabs de guitarra del juego.

Para cada cab de `data/real_cab_catalog.json` renderiza el modelo físico
(rb_core/cab_synth.py — driver por datasheet + caja por configuración + mic
+ posición) en la grilla de micrófonos/posiciones que usa Rocksmith:

    mic: dyn (SM57) · cond (TLM103) · ribbon (R121) · tube (U47 prov.)
    pos: cone (x=0.15, 1") · edge (x=0.85, 1") · offaxis (x=0.30, 2", 45°)

Los wav caen en `assets/cab_irs/RC_<CAB>_<mic>_<pos>.wav` (el instalador de
setup() los copia a <config>/nam_irs/cabs/) y `data/rb_cab_overrides.json`
se reescribe apuntando cada cab a su set — con eso `_apply_cab_override`
hace que TODAS las canciones usen estos IRs sin re-seed, y el mic-position
picker del editor los sirve como "IR propio".

Uso:  cd rig_builder && python3 tools/generate_real_cab_irs.py
"""

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE))
from rb_core import cab_synth  # noqa: E402

MICS = {"dyn": "sm57", "cond": "tlm103", "ribbon": "r121", "tube": "tube"}
POSITIONS = {
    "cone":    {"x": 0.15, "dist_in": 1.0, "angle_deg": 0.0},
    "edge":    {"x": 0.85, "dist_in": 1.0, "angle_deg": 0.0},
    "offaxis": {"x": 0.30, "dist_in": 2.0, "angle_deg": 45.0},
}


def main():
    cat = json.load(open(HERE / "data" / "real_cab_catalog.json"))
    out_dir = HERE / "assets" / "cab_irs"
    out_dir.mkdir(parents=True, exist_ok=True)

    overrides = {
        "_meta": ("OUR own cab IRs that OVERRIDE the Rocksmith-extracted "
                  "mic-position table. Generated by tools/generate_real_cab_irs.py "
                  "from the Real Cab parametric model (rb_core/cab_synth.py): "
                  "datasheet-driven drivers + per-configuration enclosure physics "
                  "+ spec-sheet mic models, validated vs measured reference grids "
                  "(see Cabs/CAB_MODELING_GUIDE.md). 100%% distributable — no "
                  "third-party IRs. One entry per cab gear key; files derive as "
                  "<ir_dir>/<prefix>_<mic>_<pos>.wav."),
    }
    n = 0
    for gear, entry in sorted(cat["cabs"].items()):
        prefix = "RC_" + gear.replace("Cab_", "")
        for mic_tok, mic in MICS.items():
            for pos_tok, pp in POSITIONS.items():
                out = out_dir / f"{prefix}_{mic_tok}_{pos_tok}.wav"
                cab_synth.synthesize_ir_wav(
                    str(out), speaker=entry["speaker"], mic=mic,
                    x=pp["x"], dist_in=pp["dist_in"], angle_deg=pp["angle_deg"],
                    drivers=int(entry["drivers"]), size_in=float(entry["size_in"]),
                    back=entry["back"], baffle_m=float(entry["baffle_m"]))
                n += 1
        overrides[gear] = {
            "ir_dir": "cabs",
            "prefix": prefix,
            "source": (f"Real Cab parametric model: {entry['speaker']} "
                       f"{entry['drivers']}x{entry['size_in']} {entry['back']}-back "
                       f"(datasheet-driven, cab_synth.py)"),
        }
        print(f"  ✓ {gear:<24} → {prefix} ({entry['speaker']} "
              f"{entry['drivers']}x{entry['size_in']} {entry['back']})")

    with open(HERE / "data" / "rb_cab_overrides.json", "w", encoding="utf-8") as fh:
        json.dump(overrides, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    print(f"\n{n} IRs → {out_dir}")
    print(f"{len(overrides) - 1} cabs registrados en rb_cab_overrides.json")


if __name__ == "__main__":
    main()
